PRACTICA4/Models/Entidades/Persona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PRACTICA4.Models.Entidades
{
    public class Persona
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
    }
}

PRACTICA4/Models/ErrorViewModel.cs
using System;

namespace PRACTICA4.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PRACTICA4/Models/PersonaCreacionModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PRACTICA4.Models
{
    public class PersonaCreacionModel
    {
        [Required(ErrorMessage ="El campo Nombre es requerido")]
        public string Nombre { get; set; }
    }
}

PRACTICA4/Models/PersonaEdicionModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PRACTICA4.Models
{
    public class PersonaEdicionModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="El campo Nombre es requerido")]
        public string  Nombre { get; set; }
    }
}

PRACTICA4/Models/PersonaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PRACTICA4.Models
{
    public class PersonaModel
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
    }
}

PRACTICA4/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PRACTICA4.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PRACTICA4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PRACTICA4/Controllers/PersonasController.cs
using Microsoft.AspNetCore.Mvc;
using PRACTICA4.Models;
using PRACTICA4.Repositorios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PRACTICA4.Controllers
{
    public class PersonasController : Controller
    {
        private readonly IPersonaRepositorio _repositorio;

        public PersonasController(IPersonaRepositorio repositorio )
        {
            _repositorio = repositorio;
        }
        public async Task<IActionResult> Index()
        {
            var listadoPersonas = await _repositorio.ObtenerTodasLasPersonas();
            return View(listadoPersonas);
        }

        public IActionResult Nuevo()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> NuevoPost(PersonaCreacionModel model)
        {
            if (ModelState.IsValid)
            {
                await _repositorio.GuardarPersona(model);
                var listadoPersonas = await _repositorio.ObtenerTodasLasPersonas();
                return View("Index", listadoPersonas);
            }

            return View("Nuevo", model);
        }

        public async Task<IActionResult> Editar([FromRoute] int id)
        {
            var model = await _repositorio.ObtenerPersonasPorId(id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditarPost(PersonaEdicionModel model)
        {
            if (ModelState.IsValid)
            {
                await _repositorio.ActualizarPersona(model);
                var listadoPersonas = await _repositorio.ObtenerTodasLasPersonas();
                return View("Index", listadoPersonas);
            }

            return View("Editar", model);
        }

        public async Task<IActionResult> EliminarPersona([FromRoute] int id)
        {
            await _repositorio.EliminarPersona(id);
            var listadoPersonas = await _repositorio.ObtenerTodasLasPersonas();
            return View("Index", listadoPersonas);
        }

    }
}

PRACTICA4/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PRACTICA4/Views/Personas/Editar.cshtml
@model PersonaEdicionModel
<h3>Editar Persona</h3>
<hr />
<div class="card">
    <div class="card-body">
        <form method="post" asp-controller="Personas" asp-action="EditarPost">
            <input type="hidden"  asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre"></label>
                <input asp-for="Nombre" type="text" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
</div>

PRACTICA4/Views/Personas/Index.cshtml
@model  List<PersonaModel>
<div class="row">
    <div class="col-md-6">
        <h3>Listado de personas</h3>
    </div>
    <div class="col-md-6">
        <a asp-controller="Personas" asp-action="Nuevo" class="btn btn-primary float-lg-right" >Nuevo</a>
    </div>
</div>
<hr />
<div class="card">
    <div class="card-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Nombre</td>
                    <td>
                        <a asp-route-id="@item.Id" asp-controller="Personas" asp-action="Editar" class="btn btn-warning">Editar</a>
                        <a asp-route-id="@item.Id" asp-controller="Personas" asp-action="EliminarPersona" class="btn btn-danger">Eliminar</a>
                    </td>
                </tr>
                } 
            </tbody>
           
        </table>
    </div>
</div>

PRACTICA4/Views/Personas/Nuevo.cshtml
@model PersonaCreacionModel
<h3>Nueva Persona</h3>
<hr />
<div class="card">
    <div class="card-body">
        <form method="post" asp-controller="Personas" asp-action="NuevoPost">
            <div class="form-group">
                <label asp-for="Nombre"></label>
                <input asp-for="Nombre" type="text" class="form-control"  />
                <span asp-validation-for="Nombre" class="text-danger" ></span>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
</div>

PRACTICA4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PRACTICA4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PRACTICA4</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personas" asp-action="Index">Mantenedor de personas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PRACTICA4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>